#!/usr/bin/env swift

import Foundation

// Paths relative to swift-astgen directory
let versionFilePath = "VERSION"
let outputFilePath = "Sources/SwiftAstGenLib/Version.swift"

// Read VERSION file
guard let versionContent = try? String(contentsOfFile: versionFilePath, encoding: .utf8) else {
    fputs("Error: VERSION file not found at \(versionFilePath)\n", stderr)
    exit(1)
}

let version = versionContent.trimmingCharacters(in: .whitespacesAndNewlines)

// Validate semver format (basic check)
let semverPattern = #"^\d+\.\d+\.\d+$"#
guard version.range(of: semverPattern, options: .regularExpression) != nil else {
    fputs("Error: VERSION file contains invalid semver format '\(version)' (expected X.Y.Z)\n", stderr)
    exit(1)
}

// Generate Version.swift content
let banner = "// AUTO-GENERATED by scripts/sync-version.swift from VERSION file. Do not edit by hand."
let body = "public let VERSION: String = \"\(version)\""
let newContent = "\(banner)\n\(body)\n"

// Check if file already has correct content
if let existingContent = try? String(contentsOfFile: outputFilePath, encoding: .utf8) {
    if existingContent == newContent {
        print("sync-version: \(outputFilePath) already up to date (version \(version))")
        exit(0)
    }
}

// Write new content
do {
    try newContent.write(toFile: outputFilePath, atomically: true, encoding: .utf8)
    print("sync-version: wrote \(outputFilePath) (version \(version))")
} catch {
    fputs("Error: Failed to write \(outputFilePath): \(error.localizedDescription)\n", stderr)
    exit(1)
}
