use serde::Deserialize;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

pub const DEFAULT_OUTPUT_PATH: &str = "./PerlNodeSyntax.scala";

#[derive(Deserialize)]
struct NodeDef {
    #[serde(rename = "type")]
    kind: String,
    named: bool,
    subtypes: Option<Vec<SubtypeDef>>,
    #[serde(default)]
    fields: HashMap<String, FieldDef>,
}

#[derive(Deserialize)]
struct SubtypeDef {
    #[serde(rename = "type")]
    kind: String,
    named: bool,
}

#[derive(Deserialize)]
struct FieldDef {
    required: bool,
    types: Vec<FieldTypeDef>,
}

#[derive(Deserialize)]
struct FieldTypeDef {
    named: bool,
}

impl FieldDef {
    fn has_named_types(&self) -> bool {
        self.types.iter().any(|t| t.named)
    }

    fn has_unnamed_types(&self) -> bool {
        self.types.iter().any(|t| !t.named)
    }
}

pub fn generate(output_path: &Path) -> Result<(), String> {
    let generated_at = chrono::Local::now()
        .format("%B %-d, %Y at %-I:%M:%S %p %Z")
        .to_string();
    let version = env!("CARGO_PKG_VERSION");
    let scala = render(ts_parser_perl::NODE_TYPES, &generated_at, version)?;
    if let Some(parent) = output_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("create dirs {}: {}", parent.display(), e))?;
        }
    }
    fs::write(output_path, scala).map_err(|e| format!("write {}: {}", output_path.display(), e))?;
    eprintln!(
        "Generated Perl AST Scala types in file: `{}`",
        output_path.display()
    );
    Ok(())
}

fn snake_to_camel(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

pub(crate) fn render(
    node_types_json: &str,
    generated_at: &str,
    version: &str,
) -> Result<String, String> {
    let nodes: Vec<NodeDef> =
        serde_json::from_str(node_types_json).map_err(|e| format!("parse node types: {}", e))?;

    let abstract_nodes: Vec<&NodeDef> = nodes
        .iter()
        .filter(|n| n.named && n.subtypes.is_some())
        .collect();

    let mut subtype_to_super: HashMap<String, String> = Default::default();
    for n in &abstract_nodes {
        for sub in n.subtypes.as_ref().unwrap() {
            if sub.named {
                subtype_to_super.insert(sub.kind.clone(), n.kind.clone());
            }
        }
    }

    let mut concrete_nodes: Vec<&NodeDef> = nodes
        .iter()
        .filter(|n| n.named && n.subtypes.is_none())
        .collect();
    concrete_nodes.sort_by_key(|n| n.kind.as_str());

    let mut abstract_sorted: Vec<&NodeDef> = abstract_nodes;
    abstract_sorted.sort_by_key(|n| n.kind.as_str());

    let mut out = String::new();

    writeln!(
        out,
        "// Automatically generated by 'perl-astgen v{} --scala-ast-only'.",
        version
    )
    .unwrap();
    writeln!(out, "// Do not edit directly!").unwrap();
    writeln!(out, "// Generated: {}", generated_at).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import ujson.Value").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "object PerlNodeSyntax {{").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "\tdef createPerlNode(json: Value): PerlNode = {{").unwrap();
    writeln!(out, "\t\tval nodeType = json(\"node_type\").str").unwrap();
    writeln!(
        out,
        "\t\t_nodeTypeMap.getOrElse(nodeType, throw new UnsupportedOperationException("
    )
    .unwrap();
    writeln!(
        out,
        "\t\t\ts\"NodeType '$$nodeType' is not a known Perl node type!\""
    )
    .unwrap();
    writeln!(out, "\t\t))(json)").unwrap();
    writeln!(out, "\t}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "\tdef tryCreatePerlNode(json: Value): Option[PerlNode] ="
    )
    .unwrap();
    writeln!(
        out,
        "\t\t_nodeTypeMap.get(json(\"node_type\").str).map(_(json))"
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "\tprivate val _nodeTypeMap: Map[String, Value => PerlNode] = Map("
    )
    .unwrap();
    let map_entries: Vec<String> = concrete_nodes
        .iter()
        .map(|n| {
            format!(
                "\t\t\"{}\" -> (json => {}(json))",
                n.kind,
                snake_to_camel(&n.kind)
            )
        })
        .collect();
    writeln!(out, "{}", map_entries.join(",\n")).unwrap();
    writeln!(out, "\t)").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "\tsealed trait PerlNode {{").unwrap();
    writeln!(out, "\t\tdef json: Value").unwrap();
    writeln!(out, "\t\tdef nodeType: String = json(\"node_type\").str").unwrap();
    writeln!(
        out,
        "\t\tdef startByte: Int = json(\"start_byte\").num.toInt"
    )
    .unwrap();
    writeln!(out, "\t\tdef endByte: Int = json(\"end_byte\").num.toInt").unwrap();
    writeln!(
        out,
        "\t\tdef startRow: Int = json(\"start_position\")(\"row\").num.toInt"
    )
    .unwrap();
    writeln!(
        out,
        "\t\tdef startColumn: Int = json(\"start_position\")(\"column\").num.toInt"
    )
    .unwrap();
    writeln!(
        out,
        "\t\tdef endRow: Int = json(\"end_position\")(\"row\").num.toInt"
    )
    .unwrap();
    writeln!(
        out,
        "\t\tdef endColumn: Int = json(\"end_position\")(\"column\").num.toInt"
    )
    .unwrap();
    writeln!(
        out,
        "\t\tdef text: Option[String] = json.obj.get(\"text\").map(_.str)"
    )
    .unwrap();
    writeln!(out, "\t\t// Field-named children are excluded here; access them via the typed lazy val accessors below.").unwrap();
    writeln!(out, "\t\tdef children: Seq[PerlNode] = json.obj").unwrap();
    writeln!(out, "\t\t\t.get(\"children\")").unwrap();
    writeln!(
        out,
        "\t\t\t.map(_.arr.toSeq.filter(c => c.obj.get(\"field_name\").isEmpty).map(createPerlNode))"
    )
    .unwrap();
    writeln!(out, "\t\t\t.getOrElse(Seq.empty)").unwrap();
    writeln!(
        out,
        "\t\t// Maps field name -> child JSON value for nodes that expose named fields."
    )
    .unwrap();
    writeln!(
        out,
        "\t\tprotected lazy val _fieldMap: Map[String, Value] ="
    )
    .unwrap();
    writeln!(out, "\t\t\tjson.obj.get(\"children\")").unwrap();
    writeln!(out, "\t\t\t\t.map(_.arr.toSeq").unwrap();
    writeln!(
        out,
        "\t\t\t\t\t.filter(c => c.obj.get(\"field_name\").exists(_.str.nonEmpty))"
    )
    .unwrap();
    writeln!(out, "\t\t\t\t\t.map(c => c(\"field_name\").str -> c)").unwrap();
    writeln!(out, "\t\t\t\t\t.toMap)").unwrap();
    writeln!(out, "\t\t\t\t.getOrElse(Map.empty)").unwrap();
    writeln!(out, "\t}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "\t// Abstract supertype traits:").unwrap();
    for n in &abstract_sorted {
        writeln!(
            out,
            "\tsealed trait {} extends PerlNode",
            snake_to_camel(&n.kind)
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "\t// Concrete node types:").unwrap();
    for n in &concrete_nodes {
        let scala_name = snake_to_camel(&n.kind);
        let extends = match subtype_to_super.get(&n.kind) {
            Some(super_kind) => snake_to_camel(super_kind),
            None => "PerlNode".to_owned(),
        };

        // Collect all fields (sorted for determinism)
        let mut all_fields: Vec<(&String, &FieldDef)> = n.fields.iter().collect();
        all_fields.sort_by_key(|(name, _)| name.as_str());

        if all_fields.is_empty() {
            writeln!(
                out,
                "\tcase class {}(json: Value) extends {}",
                scala_name, extends
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "\tcase class {}(json: Value) extends {} {{",
                scala_name, extends
            )
            .unwrap();
            for (field_name, fd) in &all_fields {
                let scala_name = if field_name.as_str() == "type" { "tpe" } else { field_name.as_str() };
                if fd.has_named_types() {
                    if fd.has_unnamed_types() {
                        // Mixed field: unnamed tokens (e.g. parentheses) may appear as the child.
                        // Always Option[PerlNode] — None when the actual child is a token.
                        writeln!(
                            out,
                            "\t\tlazy val {}: Option[PerlNode] = _fieldMap.get(\"{}\").flatMap(tryCreatePerlNode)",
                            scala_name, field_name
                        )
                        .unwrap();
                    } else if fd.required {
                        writeln!(
                            out,
                            "\t\tlazy val {}: PerlNode = createPerlNode(_fieldMap(\"{}\"))",
                            scala_name, field_name
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            out,
                            "\t\tlazy val {}: Option[PerlNode] = _fieldMap.get(\"{}\").map(createPerlNode)",
                            scala_name, field_name
                        )
                        .unwrap();
                    }
                } else {
                    // Token-only field: expose as String
                    if fd.required {
                        writeln!(
                            out,
                            "\t\tlazy val {}: String = _fieldMap(\"{}\")(\"text\").str",
                            scala_name, field_name
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            out,
                            "\t\tlazy val {}: Option[String] = _fieldMap.get(\"{}\").flatMap(_.obj.get(\"text\").map(_.str))",
                            scala_name, field_name
                        )
                        .unwrap();
                    }
                }
            }
            writeln!(out, "\t}}").unwrap();
        }
    }
    writeln!(out).unwrap();
    writeln!(out, "}}").unwrap();

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snake_to_camel_converts() {
        assert_eq!(snake_to_camel("source_file"), "SourceFile");
        assert_eq!(snake_to_camel("binary_expression"), "BinaryExpression");
        assert_eq!(snake_to_camel("postfix_deref"), "PostfixDeref");
        assert_eq!(snake_to_camel("number"), "Number");
    }

    #[test]
    fn render_produces_valid_scala() {
        let scala = render(
            ts_parser_perl::NODE_TYPES,
            "July 17, 2026 at 12:00:00 AM UTC",
            "0.1.0",
        )
        .expect("render should succeed");
        assert!(
            scala.contains("object PerlNodeSyntax {"),
            "missing object header"
        );
        assert!(
            scala.contains("sealed trait PerlNode {"),
            "missing PerlNode trait"
        );
        assert!(
            scala.contains("sealed trait PostfixDeref extends PerlNode"),
            "missing abstract trait"
        );
        assert!(
            scala.contains("case class SourceFile(json: Value) extends PerlNode"),
            "missing SourceFile"
        );
        assert!(
            scala.contains("case class AmperDerefExpression(json: Value) extends PostfixDeref"),
            "missing subtype class"
        );
        assert!(
            scala.contains("def createPerlNode(json: Value): PerlNode ="),
            "missing factory"
        );
        assert!(
            scala.contains("def children: Seq[PerlNode]"),
            "missing children accessor"
        );
        assert!(
            scala.contains("def text: Option[String]"),
            "missing text accessor"
        );
    }

    #[test]
    fn binary_expression_has_field_accessors() {
        let scala = render(
            ts_parser_perl::NODE_TYPES,
            "July 18, 2026 at 12:00:00 AM UTC",
            "0.1.0",
        )
        .expect("render should succeed");
        assert!(
            scala.contains("case class BinaryExpression(json: Value) extends PerlNode {"),
            "BinaryExpression should open a body block"
        );
        // left/right are mixed fields (named nodes + unnamed parens) → Option[PerlNode]
        assert!(
            scala.contains("lazy val left: Option[PerlNode] = _fieldMap.get(\"left\").flatMap(tryCreatePerlNode)"),
            "missing BinaryExpression.left accessor"
        );
        assert!(
            scala.contains("lazy val right: Option[PerlNode] = _fieldMap.get(\"right\").flatMap(tryCreatePerlNode)"),
            "missing BinaryExpression.right accessor"
        );
        // operator is token-only — must be a String accessor
        assert!(
            scala.contains("lazy val operator: String = _fieldMap(\"operator\")(\"text\").str"),
            "missing BinaryExpression.operator String accessor"
        );
    }

    #[test]
    fn method_call_expression_has_optional_arguments() {
        let scala = render(
            ts_parser_perl::NODE_TYPES,
            "July 18, 2026 at 12:00:00 AM UTC",
            "0.1.0",
        )
        .expect("render should succeed");
        // arguments and invocant are mixed fields → Option[PerlNode] via tryCreatePerlNode
        assert!(
            scala.contains(
                "lazy val arguments: Option[PerlNode] = _fieldMap.get(\"arguments\").flatMap(tryCreatePerlNode)"
            ),
            "missing MethodCallExpression.arguments accessor"
        );
        assert!(
            scala.contains("lazy val invocant: Option[PerlNode] = _fieldMap.get(\"invocant\").flatMap(tryCreatePerlNode)"),
            "missing MethodCallExpression.invocant accessor"
        );
        // method is named-only and required → PerlNode
        assert!(
            scala.contains("lazy val method: PerlNode = createPerlNode(_fieldMap(\"method\"))"),
            "missing MethodCallExpression.method accessor"
        );
    }

    #[test]
    fn field_map_helper_in_perl_node_trait() {
        let scala = render(
            ts_parser_perl::NODE_TYPES,
            "July 18, 2026 at 12:00:00 AM UTC",
            "0.1.0",
        )
        .expect("render should succeed");
        assert!(
            scala.contains("protected lazy val _fieldMap: Map[String, Value]"),
            "missing _fieldMap in PerlNode trait"
        );
    }

    #[test]
    fn token_only_field_emits_string_accessor() {
        let scala = render(
            ts_parser_perl::NODE_TYPES,
            "July 18, 2026 at 12:00:00 AM UTC",
            "0.1.0",
        )
        .expect("render should succeed");
        // binary_expression.operator is required + token-only → String
        assert!(
            scala.contains("lazy val operator: String = _fieldMap(\"operator\")(\"text\").str"),
            "token-only required field should be a String accessor"
        );
        // Must NOT be a PerlNode accessor
        assert!(
            !scala.contains("lazy val operator: PerlNode"),
            "token-only field must not be PerlNode"
        );
        assert!(
            !scala.contains("lazy val operator: Option[PerlNode]"),
            "token-only field must not be Option[PerlNode]"
        );
    }
}
