#!/usr/bin/env bun
// Reads package.json#version and writes it to src/version.ts so the CLI
// reports the same version that npm publishes. Wired up via the `prebinary`
// script in package.json and invoked by bump-version.sh after editing the
// canonical version in package.json.
//
// The generated file is committed so reviewers can see the change in PRs.
import {readFileSync, writeFileSync} from "node:fs"
import {fileURLToPath} from "node:url"
import {dirname, join} from "node:path"

const here = dirname(fileURLToPath(import.meta.url))
const repo = dirname(here)
const pkgPath = join(repo, "package.json")
const outPath = join(repo, "src", "version.ts")

const pkg: { version?: unknown } = JSON.parse(readFileSync(pkgPath, "utf8"))
if (typeof pkg.version !== "string" || pkg.version.length === 0) {
    throw new Error(`package.json at ${pkgPath} is missing a version field`)
}

const banner = "// AUTO-GENERATED by scripts/sync-version.ts from package.json. Do not edit by hand."
const body = `export const VERSION: string = ${JSON.stringify(pkg.version)}\n`
const next = `${banner}\n${body}`

let prev = ""
try {
    prev = readFileSync(outPath, "utf8")
} catch {
    // file does not exist yet
}

if (prev !== next) {
    writeFileSync(outPath, next)
    console.log(`sync-version: wrote ${outPath} (version ${pkg.version})`)
} else {
    console.log(`sync-version: ${outPath} already up to date (version ${pkg.version})`)
}
